version: '2'
services:
  todofiapgateway-postgresql:
    image: postgres:12.1
    # volumes:
    #     - ~/volumes/jhipster/todofiapgateway/postgresql/:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=todofiapgateway
      - POSTGRES_PASSWORD=
    ports:
      - 5432:5432
